services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: chef_starz-backend
    container_name: chef_starz-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    restart: always
