# Generated by Django 6.0.2 on 2026-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userblockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
