# Generated by Django 6.0.2 on 2026-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customusermodel_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
