# Generated by Django 6.0.2 on 2026-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_reportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='target_type',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('comment', 'Comment'), ('user', 'User'), ('post', 'Post')], max_length=20),
        ),
    ]
