# Generated by Django 6.0.2 on 2026-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
